#!/bin/bash
#                                                                  mk Jan 2014
# Script to extract last frames of job directories for a quick view.   

###      not complete!!!

# -----------------------------------------------------------------------------
# This will create loader files to read in sequential namd dcd runs 
# with a single script.
#
source ../Scripts/common_functions.sh

#-- create a local version of a dcd_loader file: 
combined="quickview_loader_script"

#-- make a temporary data directory: 
if [ -d temp_data_dir ];
then
 rm -rf temp_data_dir
fi
mkdir temp_data_dir

#-- write header to file: 
echo "#!/usr/local/bin/vmd " >$combined.vmd
echo "# VMD script written by save_state $Revision: 1.44 $" >>$combined.vmd
echo "# VMD version: 1.9.1" >>$combined.vmd

# -- Source master_config_file: -----------------------------------------------
read_master_config_file ../Setup_and_Config

 
# change to main job directory: 
cd ../

# --Check for existing directories under /MainJob_dir and grab "official" directory list. 
 
if [ "$(ls -A $JOB_DIR)" ]; then

# source directory list. 
y=$(cat .dir_list.txt) 

cd $JOB_DIR

for i in $y
do
# --Extract dcd file locations into /CollectiveData/dcd_job_loader_file.vmd
 cd $i

# grab directory name
 echo -e " Extracting coor file details in directory $JOB_DIR/$i \n "
 ../../Scripts/Analysis_Scripts/create_dcd_loader_script 

# merge files: 
 cat OutputFiles/local_dcd_file_loader.vmd  >> ../../Analysis/$combined.vmd 
 cd ../
 
done
fi

echo -e " Extracted locations of dcd files from the /MainJob_dir in $combined.vmd" 
echo -e " Setup files written to basic_vmd_setup.vmd " 
echo -e " Make sure to check basic_vmd_setup.vmd is pointing to the right files! " 

cd ../Analysis


